source "https://rubygems.org"

ruby "3.3.6"

gem "rails", "~> 8.0.2"
gem "pg", "~> 1.1"
gem "puma", "~> 6.4"
gem "tzinfo-data", platforms: %i[windows jruby]
gem "bootsnap", require: false
gem "rack-cors"

group :development, :test do
  gem "debug", platforms: %i[mri windows], require: "debug/prelude"
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
  gem "rspec-rails", "~> 7.0"
  gem "factory_bot_rails", "~> 6.4"
  gem 'faker'
end

group :test do
  gem "shoulda-matchers", "~> 6.0"
  gem "database_cleaner-active_record", "~> 2.2"
  gem "simplecov", require: false
end
